name = "TransformsBase"
uuid = "28dd2a49-a57a-4bfb-84ca-1a49db9b96b8"
authors = ["Júlio Hoffimann <julio.hoffimann@gmail.com> and contributors"]
version = "1.2.1"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"

[compat]
AbstractTrees = "0.4"
InverseFunctions = "0.1"
julia = "1"
