name = "TransformsBase"
uuid = "28dd2a49-a57a-4bfb-84ca-1a49db9b96b8"
authors = ["Júlio Hoffimann <julio.hoffimann@gmail.com> and contributors"]
version = "1.5.1"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"

[compat]
AbstractTrees = "0.4"
julia = "1"
